exp_id: racer
tasks: all
bs: 3  # 3->12GB   6->22GB, 12 -> 44GB
num_workers: 3
epochs: 15
sample_distribution_mode: task_uniform
lang_model_name: t5-11b
lang_level: task
image_size: 256

peract:
  add_rgc_loss: true
  lambda_weight_l2: 1.0e-06
  lr: 0.0005
  warmup_steps: 2000
  warmup_proportion: 0.08
  optimizer_type: lamb
  lr_cos_dec: True
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]
rvt:
  place_with_mean: False

